### ISSUE TITLE
Reposition Old View

### ISSUE THREAD

**Issue by ErAshu** [EngrAhsanAli/AADraggableView#1]
Hi Ahsan ALi,
Actually i want a new feature in this demo. I have drag only one view at a time , if user drag second then old dragged view should go its own original position. If this already in this then please let me know which method i have to use. 

Thanks.

**Comment by EngrAhsanAli** [comment]
Hello ErAshu,

Yea, its quite simple, you only need to implement the delegate method `draggingDidEnd` and re-position the old Views in that. But you need to save the initial/updated positions of all of your views. Give it a try and let me know, thanks for your interest.

**Comment by ErAshu** [comment]
Hello Ahsan,
I have already done it by delegate method `draggingDidBegan` 

Thanks for your reply. 👍
